default_context:
  project_name: 'startup-together'
  project_slug: 'startup-together'
  domain_main: 'startup-together.com'
  domain_staging: 'stag.startup-together.com'
  docker_swarm_stack_name_main: 'startup-together-com'
  docker_swarm_stack_name_staging: 'stag-startup-together-com'
  secret_key: '(-2#ey&$kh-(0o!i-+=maa@4!==*b!i(_7h(mj#!*b641y+9p4'
  first_superuser: 'admin@startup-together.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.startup-together.com", "https://stag.startup-together.com", "https://startup-together.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@startup-together.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: 'startup-together.com'
  traefik_constraint_tag_staging: 'stag.startup-together.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: 'https://607eeeaaa8f94deaa7f8c5e705a368e2@o956691.ingest.sentry.io/5906086'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
