name: Publish backend

on:
  push:
    paths:
      - 'backend/.version'
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: backend


jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Read Docker Image Identifiers
        run: echo REGISTRY_USERNAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Set registry package link
        run: echo REGISTRY_PACKAGE=${{ env.REGISTRY }}/${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }} >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/test

      - name: Get version
        run: echo VERSION=$(cat backend/.version) >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./backend/backend.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY_PACKAGE }}:latest,${{ env.REGISTRY_PACKAGE }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
